### ISSUE TITLE
Project won't compile without file for google maps API key

### ISSUE THREAD

**Issue by mcoffin** [flysight/flysight-viewer-qt#106]
Without the `secrets.h` file (containing the Google Maps API key for the application), the project fails to compile. I don't know what the best practices are for that API key (I'll look it up later today when I have time), but at the *very least*, this should be documented and a blank once included in its place I would think -- so that at least compilation would succeed.

```
mapview.cpp:33:10: fatal error: secrets.h: No such file or directory
```

**Comment by crwper** [comment]
Good point. I don't think the API key itself can be shared, as Google now charges for Maps API use and putting the key in the wild would mean any product could use it. However, it should be possible, e.g., to include a template header file with blank entries where API keys should be.

**Comment by crwper** [comment]
Thanks, @mcoffin and @ntroncos. I've added a dummy "secrets.h" to the repo. If you add your own API key and don't want to commit the changes, I think the best solution may be to follow the advice here:

https://wildlyinaccurate.com/git-ignore-changes-in-already-tracked-files/
