### ISSUE TITLE
Disappearing floating windows

### ISSUE THREAD

**Issue by ColOfAbRiX** [flysight/flysight-viewer-qt#153]
Hi!

I'm running Flysight Viewer in windows and I'm running into a problem where floating windows (like Map View or Drag Polar) completely disappear and I haven't found a way to fix this problem.

I'm using the latest published version of flysight viewer for windows and I have this problem on 3 different machines with Windows 10, and Windows 8.

I don't have a full procedure to replicate the issue because I'm not sure what I do to make the issue happening, here is what I have:

* detach one of the windows, like Map View, and make it a float window
* move it for example at the edge of the screen (this is the bit I'm not sure)
* when I release the mouse, or even before, the window disappear

From this point onward going in the menu and reselecting the view won't bring it back. The respective menu item is always unckecked.

I'm looking for any way I can restore them, even a hack. For example, is there a way to reset the status of the windows? Where is this configuration stored? Somewhere on disk or in the windows registry?

Thank you!

**Comment by crwper** [comment]
Sorry for the delay in getting back to you on this. For some reason I didn't receive a notification.

This is a known issue with the docking windows--there are cases where the window disappears and can't be found anywhere. It's possible to fix this by resetting FlySight Viewer's preferences. This will also reset things like the colour settings, but won't affect your logbook.

On Windows, this can be done as follows (be very careful here, as the WIndows registry contains saved settings for all your software):

1. Hit the Windows key on your keyboard.
2. Type "regedit" when the start menu comes up, then hit Enter. When prompted, allow the app to make changes to your device.
3. In Registry Editor, open the "Computer" folder, then "HKEY_CURRENT_USER", then "Software", then "FlySight".
4. Inside the "FlySight" folder, right-click the "Viewer" folder and choose "Delete" from the context menu. Confirm that the "Viewer" folder is selected, then click "Yes" to confirm that you want to delete this key and all its subkeys.
5. Close Registry Editor.

On Mac:

1. Go to the desktop, then in the meny choose Go > Go to Folder.
2. A dialog box will come up asking for a location you want to go to. Enter "~/Library/Preferences".
3. Look for "com.flysight.Viewer.plist". Optionally, copy this file somewhere else if you want to keep a backup. Then delete the original.

**Comment by ColOfAbRiX** [comment]
No prob for the delay! Thank you so much, I'll try this as soon as I can.

**Comment by ColOfAbRiX** [comment]
It worked, thank you!
