### ISSUE TITLE
Speed - Calculated Scoring higher than graph (FS2)

### ISSUE THREAD

**Issue by boulavogue** [flysight/flysight-viewer-qt#154]
I've noted on a few jumps that the calculated score (avg 3 sec) is higher than any one point on the graphed vertical speed. Example file & screenshot for reference. 
FS2 - v2023.07.01
FlySightViewer-Win-20230729
[TRACK.CSV](https://github.com/user-attachments/files/16511396/TRACK.CSV)
![image](https://github.com/user-attachments/assets/ca30ec0f-1180-4bd7-876b-c4f994ff4147)

**Comment by boulavogue** [comment]
Example 2 - Speed accuracy above 2, but the file above is below speed accuracy  2....
[TRACK.CSV](https://github.com/user-attachments/files/16511519/TRACK.CSV)

**Comment by boulavogue** [comment]
Re-opening, as the fastest vertical speed in the window (496.139) is slower than the "Results" 3 sec avg vertical speed (496.61)
![image](https://github.com/user-attachments/assets/e00fa0ed-fad2-445a-9a14-a92dc8ed3c52)
[TRACK.CSV](https://github.com/user-attachments/files/16522165/TRACK.CSV)

**Comment by crwper** [comment]
This is normal. The score is calculated using the difference in elevation over a 3 second window, whereas the vertical speeds are instantaneous measurements based on the Doppler shift in satellite signals. It's possible to compare the two, but you need to take the accuracy estimates into account. Using the first track you uploaded as an example:

The calculated score is 497.83 +/- 8.64 km/h (i.e., the value of 2.400 m/s shown in the scoring window)
The average vertical speed over the same window is 494.19 +/- 2.607 km/h (the average of the speed accuracy estimate)

The accuracy estimates given here are "1 sigma" values, which means roughly 68% of the time the true measurement will be within that margin of the reported value. Loosely speaking, as long as these two ranges overlap (as they do here), it's likely the two numbers represent the same performance.

**Comment by boulavogue** [comment]
@crwper thank you so much for this concise and insightful explanation. I did not realize the calculated score was from the elevation difference. I looked for a "buy me a coffee" donation button on the FS page, but I'll get you a beverage at the world champs. Many thanks!!
