### ISSUE TITLE
FlareScoring.h missing

### ISSUE THREAD

**Issue by Akegata** [flysight/flysight-viewer-qt#87]
I'm trying to build the flysight viewer on an ubuntu box.
I get the error "flareform.cpp:11:26: fatal error: FlareScoring.h: No such file or directory", which makes sense since flareform.cpp has the line "#include "FlareScoring.h"", but there is no FlareScoring.h in the current source.

**Comment by crwper** [comment]
Are you building from the latest commit? I cloned https://github.com/flysight/flysight.git and built commit `85bf...`. This seemed to work without issues and the source on that commit definitely includes `FlareScoring.h`.

**Comment by Akegata** [comment]
I am indeed not using that commit. I cloned the same URL as you, but I can't see a 85bf... commit in the git log. The last commit available is 81ce1233ab823a496190826960d2247fd08c3637, from March 13, so I guess I can't access the latest commits for some reason?

**Comment by crwper** [comment]
Ah, shoot, I gave the wrong URL. I actually cloned from https://github.com/flysight/flysight-viewer-qt.git, where the latest commit should come up as `85bf...`. The other link I gave is for the firmware.

**Comment by crwper** [comment]
Just tried logging out and following the link just to be sure, and that does seem to be the latest commit on that repository.

**Comment by Akegata** [comment]
That makes sense.
The error is sort of present (although not really) in the correct git repo.
flareform.cpp includes "FlareScoring.h", but the file is called flarescoring.h (with no caps). I changed that in my clone, it compiles fine now. Thanks!

**Comment by crwper** [comment]
Aha! Thanks. I will fix this in the main repo right away.
